routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->name('homepage');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/logout', '\App\Http\Controllers\Auth\LoginController@logout');

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('client', 'ClientController');
Route::resource('privilege', 'PrivilegeController');
Route::resource('abonnement', 'CarteController');
Route::resource('marchand', 'MarchandController');
Route::get('/Acceuil', function() {
        return view ('frontoffice.Acceuil');
});
Route::get('/Propos', function() {
    return view ('frontoffice.Propos');
});
Route::get('/editc/{$id}', function() {
    return view ('frontoffice.editc');
});
Route::get('/clientAcc', 'ClientController@clienthome');
Route::get('/Acceuil', function() {
    return view ('frontoffice.Acceuil');
});
Route::get('/Ajoutprivi', function() {
    return view ('frontoffice.Ajoutprivi');
});


Route::get('/createc','ClientController@create');
Route::get('/createm','MarchandController@create');

Route::POST('/client/update/{id}','ClientController@updateClient')->name('update_client');
Route::POST('/client/home','ClientController@loginuser')->name('loginuser');
Route::get('/logoutclient','ClientController@logout')->name('logoutclient');
Route::get('/client','ClientController@index') ;
Route::get('/logasclient',function(){
    return view ('frontoffice.Client');
}) ;

Route::get('/marchandAcc', 'MarchandController@marchand_acceuil');
Route::get('/logasmarchand','MarchandController@logininter');
Route::get('/marchand/ajout/acheteur/{id}','MarchandController@ajoutacheteur')->name('_ajoutacheteur');
Route::get('/logoutmarchand','MarchandController@logout')->name('logoutmarchand');
Route::POST('/logasmarchand','MarchandController@login')->name('login_marchand') ;
Route::POST('/marchand/ajout/privilege','MarchandController@ajoutprivilege')->name('ajoutprivilege');
Route::POST('/marchand/add/priv','PrivilegeController@addpriv')->name('addpriv');
Route::POST('/marchand/update','MarchandController@update')->name('update_marchand');

    // Route::get('/editm', function() {
    
    //     return view ('frontoffice.editm');
    // });
Route::group(['prefix' => 'admin',  'middleware' => 'auth'], function()
{
    Route::get('dashboard', function() {} );
});

resources/views/frontoffice/Acceuil.blade.php
@extends('frontoffice.acc')
  
@section('contents')

        
            <br> 
            <br> 

                <div class="card mb-3" style="max-width: 1800px;"  >
                    <div class="container">
                        <div class="row no-gutters">
                          
                          <div class="col-md-8">
                            <div class="card-body" align="center">
                                <br> 
                                <br> 
                              <h3 class="card-title"> 
                                    <p class="text-secondary"> Faites des bons affaires  et  Participez  <br> au Club Priviléges BigDeal ! </p></h3>
                              <h5 class="card-text">
                              Des Priviléges, Retrouvez  les meilleurs remise au cours  chez vous commerçants et profitez de vos produit et de service et préfere à prix malins via la Carte Priviléges .
                                    N'attez  Plus télecharger l'Application <br> <p class="text-warning">  Club-BigDeal ! </p>  <br> ICI maintenant Pour consultez les Priviléges 
                      . </h5> 
                              <p class="card-text"><small class="text-muted">  <br> <a href="https://play.google.com/store/apps/details?id=com.clubprivileges&hl=fr"><img src="{{url('image/ggp.png')}}" alt="playstore"></a>
                                <a href="https://play.google.com/store/apps/details?id=com.clubprivileges&hl=fr"><img src="{{url('image/app.jpg')}}" alt="appstore"  width=150 ></a></small></p>
                            </div>
                          </div>
                          <div class="col-md-4.offset-md-4">
                                <img src="{{url('image/tlfn.PNG')}}" class="card-img" alt="club" width=250  height="450">
                          </div>
                              <br> 
                              <br>
                          </div>
                      </div>  
       
              </div>
          
              <section class="price-area pricing-area section-big" id="avantages">
                    <div class="container">
                        <div class="row">
            
                            <div class="section-title">
                                <h2> Pourquoi s’abonner au club privilèges ?</h2>
                                <p>Être membre du Club Privilèges, c’est accéder à un monde d’avantages<br>
            d’exceptions avec des remises permanentes<br>
            et exclusives chez nos partenaires.
                                </p>
                            </div>
                        </div>
                        <div class="row about-content">
                            <div class="col-xs-12 col-sm-4">
                                <div class="price-box wow fadeInUp" data-wow-delay="0.3s">
                                    <h4 class="text-info"> <u> Le  Club privilèges </u></h4>
                                    <ul>
                                        <li>Une carte privilèges</li>
                                        <li>Une application mobile</li>
                                        <li>Des remises jusqu’à 35%</li>
                                        <li>+100 partenaires</li>
                                         <li>Remise valables toute l'année</li>
                                    </ul>
                                  
                                    <h4 class="price-rate"> Engagement annuel</h3>
                                    
                                    
                                </div>
                            </div>
                            
                                
                             <div class="col-xs-12 col-sm-4   wow fadeInUp" data-wow-delay="0.3s">
                                <img src="https://club.bigdeal.tn/frontend/bigdeal/images/carte-one.png" class="img-responsive" alt="img">
                            </div>
                            
                        </div>
                    </div>
                </section>
           


     

@endsection

resources/views/frontoffice/Ajoutacheteur.blade.php
@extends('frontoffice.acc')
@section('contents')

<div class="container" >
    <br>
    <br>

<h4 class="text-info"> <u> Ajouter un Acheteur </u> </h4>

@if ($errors->any())
    <div class="alert alert-danger">
        <strong>Whoops!</strong> Something went wrong<br>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
<hr>
<form  action="{{route('ajoutprivilege')}}" method="POST">
@csrf
    <div class="form-row">
      <div class="form-group col-md-6">
        <label> ID Carte  <abbr class="required">*</abbr> </label>
        <input type="number" class="form-control" name="carte_id" placeholder=" Identifiant du client ">
      </div>
      <div class="form-group col-md-6">
        <label> Nom et Prénom <abbr class="required">*</abbr></label>
        <input type="text" class="form-control" name="nom" placeholder=" Nom & prénom ">
      </div>
    </div>
    
    <div class="form-group">
        <label> ID privilège <abbr class="">*</abbr></label>
          <select name="privilege_id" class="custom-select">
          @if(empty($marchand->privilege->all()))
              <option selected disabled >You dont have any offers yet</option>
          @else
            @foreach($marchand->privilege as $key=>$value)
              <option selected value="{{$value->id}}">{{$value->id}}</option>
            @endforeach
          @endif
        </select>
    </div>
    
    <div class="form-row">
      <div class="form-group col-md-6">
        <label> date d'achat <abbr class="">*</abbr></label>
        <input type="date" class="form-control" name="created_at"min="2019-01-01" max="2050-12-31">
      </div>

      <div class="form-group col-md-6">
        <label>Adresse <abbr class="required">*</abbr> </label>
        <input type="String" class="form-control" name="Adresse" >
      </div>
    </div>

          <br>
           <br>
           <div class="form-row">
           <div class="form-group col-md-6" align="center">
                <br>
                <button  type="submit" class="btn btn-warning btn-lg btn-block">  Ajouter un Acheteur </button> </a>
           </div>
           </div>

    <br>
    <br>
  </form>
</div>
@endsection

resources/views/frontoffice/Ajoutprivi.blade.php
@extends('frontoffice.acc')
@section('contents')
<div class="container" >
    <br>
    <br>

<h4 class="text-info"> <u> Ajouter un Privilège </u> </h4>

@if ($errors->any())
    <div class="alert alert-danger">
        <strong>Whoops!</strong> Something went wrong<br>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
<hr>
<form method="POST" action="{{route('addpriv')}}">
    @csrf
    <div class="form-row">
      <div class="form-group col-md-6">
        <label> Nom <abbr class="required">*</abbr> </label>
        <input type="nom" class="form-control" name="nompriv" placeholder="Nom ">
      </div>
      <div class="form-group col-md-6">
        <label> Remise  <abbr class="required">*</abbr></label>
        <input type="decimal" class="form-control" name="remise" placeholder="Remise">
      </div>
    </div>
    <div class="form-group">
            <label>Description du privilège <abbr class="required">*</abbr></label>
      <textarea type="text" class="form-control" name="descrip" placeholder="Toutes les dicription du priviléges"> </textarea>
    </div>
    <div class="form-row">
      <div class="form-group col-md-6">
        <label>Date-Début <abbr class="required">*</abbr></label>
        <input type="date" class="form-control" name="datedep"min="2019-01-01" max="2050-12-31">
      </div>
      <div class="form-group col-md-4">
        <label>Date-Fin <abbr class="required">*</abbr> </label>
        <input type="date" class="form-control" name="datefin" min="2019-01-01" max="2050-12-31">
      </div>
    </div >
          <br>
           <br>
           <div class="form-row">
           <div class="form-group col-md-6" align="center">
                <br>
                <button  type="submit" class="btn btn-info btn-lg btn-block">  Ajouter un privilège  </button> </a>
           </div>
           </div>

    <br>
    <br>
  </form>
</div>
@endsection

resources/views/frontoffice/Client.blade.php
@extends('frontoffice.acc')
@section('contents')

@if (\Session::has('error'))
      <div class="alert alert-danger">
        <p>{{ \Session::get('error') }}</p>
      </div><br />

     @endif
@if (\Session::has('success'))
    <div class="alert alert-success" role="alert">
        {{ session('success') }}
    </div>
@endif


<div class ="container">
      <br>
      <br>

    <img src="https://club.bigdeal.tn/frontend/bigdeal/images/1.png" class="rounded mx-auto d-block">
                  <br>

                 <br>
           <div class="section-title">
                <h2 class="text-primary">  Connexion  au Club:  </h2>
                     <p>
                        <form method="POST" action="{{ route('loginuser') }}" >
                          @csrf
                                <div class="form-group">
                                  <label class="required"> Saisir ID du carte : </label>
                                  <input name="carte_id" type="text"   placeholder="8 caractères ">
                                  <small id="emailHelp" class="form-text text-muted">( champ obligatoire *) .</small>
                                </div>
                                <input type="submit"  class="btn btn-warning"  value="Login">
                        </form>
                      </p>
            </div>
            <br>
           <hr align="center" width="100%">
           <div class="section-title" align="center">
                            <h2  class="text-success"> Comment Adhérer au club !</h2>
                     <p class="text-secondary">Pour vous inscrire au Club Privilèges vous n’avez qu’à remplir le formulaire ci-dessous.<br>
               vous recevrez votre carte membre à l'adresse mentionnée dans les 48 heures.
                     <br> <p><a href="{{url('createc')}}" class="text-primary"><b><h5> Inscriver-vous ICI  </h5></b></a></p>
                      </p>


            </div>

</div></div>

@endsection

resources/views/frontoffice/Marchand.blade.php
@extends('frontoffice.acc')
@section('contents')




<div class ="container">
  @if (\Session::has('errors'))

    <div class="alert alert-danger">
        <strong>Whoops!</strong> Something went wrong<br>
        <div class="alert alert-danger" role="alert">
          {{ session('errors') }}
        </div>
    </div>
@endif
@if (\Session::has('success'))
    <div class="alert alert-success" role="alert">
        {{ session('success') }}
    </div>
@endif
      <br>
      <br>

    <img src="https://club.bigdeal.tn/frontend/bigdeal/images/1.png" class="rounded mx-auto d-block">
                  <br>

                 <br>
           <div class="section-title">
                <h3 class="text-info">  Adhérer au Club:  </h3>

                     <p>
                            <form action = "{{route('login_marchand')}}" method="POST" >
                              @csrf
                                    <div class="form-group">
                                      <label>E-mail  </label>
                                      <input type="email" class="form-control" name="email"  placeholder="foulenbenfoulen@mail.com">
                                      <small  class="form-text text-muted">saisir votre email.</small>
                                    </div>
                                    <div class="form-group">
                                      <label> Mot de passe </label>
                                      <input type="password" class="form-control" name="password" placeholder="Mot de passe">
                                    </div>
                                    <div class="form-group form-check">
                                      <input type="checkbox" class="form-check-input" id="exampleCheck1">
                                      <label class="form-check-label" for="exampleCheck1"> enregistrer le mot de passe </label>
                                    </div>
                                    <input type="submit" class="btn btn-warning" value="Connexion ">  
                                  </form>
                      </p>
            </div>
            <br>
           <hr align="center" width="100%">
           <div class="section-title" align="center">
                            <h2  class="text-success"> Comment Adhérer au club !</h2>
                     <p class="text-secondary">Pour vous inscrire au Club Privilèges vous n’avez qu’à remplir le formulaire ci-dessous.<br>
               vous pouvez consulter et publier les Privilèges .
                     <br> <p><a href="{{url('createm')}}"> <b class="text-primary"> Inscriver-Vous </b></a></p>
                      </p>


            </div>

</div></div>

@endsection

resources/views/frontoffice/Propos.blade.php
@extends('frontoffice.acc')
@section('contents')

<div class="container"></div>

<div class="clearfix space"></div>
        <section  class="our-contact section-big pdt">
        <div class="container">
            <div class="row">
                <div class="section-title" align="center">
                    <h2 align="center" class="text-info">Qui sommes-nous</h2>
                </div>
			</div>



	<div class="condition"><p><b class="text-primary"> À propos de B!GDeal
</b></p><p>Nous sommes une startup tunisienne lancée en mai 2012 par notre fondateur Issam Essefi, notre mission est de mettre à disposition de nos Clients le savoir faire et la technologie  adéquate afin de proposer de bons plans et de les rendre accessibles à tous !</p><p>
</p><p>En janvier 2018, b!gdeal a rejoint le groupe Medianet, leader en ingénierie informatique et web service créé en 1998, propulsé par Africinvest, b!gdeal s'est lancé en avril 2019 en côte d'ivoire (www.bigdeal.ci)</p><p>Nous employons plus de 20 personnes à Tunis et à Abidjan  et nous comptons aller plus loin.</p><p>Bigdeal S.A est membre du syndicat du e-commerce et de la vente à distance <a href="http://www.sevad.tn/" target="_blank">(SEVAD)</a></p><p>
</p><p ><b class="text-primary">À propos du club privilèges by BIGDeal
</b></p><p>Club privilèges by b!gdeal est un abonnement donnant droit à ses membres de profiter d’avantages&nbsp; et de remises exclusifs dans l’ensemble du réseau des enseignes participantes.
</p><p>L’application gratuite Club privilèges by bigdeal permet à ses utilisateurs de profiter des avantages exclusifs spécialement négociés auprès des enseignes de proximités.</p><p>Plus de 100 enseignes sont déjà partenaires du club privilèges by bigdeal : Fatales, gourmandise, California Gym, L'occitane de province,  des restaurants, des hôtels, des agences de voyage et bien d'autres...<br>Chaque semaine, des dizaines de nouvelles enseignes nous rejoignent.
</p><p><br></p><p><br></p></div>




        </div>
    </section>


    </div>

@endsection

resources/views/frontoffice/clientAcc.blade.php
@extends('frontoffice.acc')
@section('contents')
@if (\Session::has('success'))
      <div class="alert alert-success">
        <p>{{ \Session::get('success') }}</p>
        <?php
        session()->forget('success') ;
        ?>
      </div><br />

     @endif
<br>
 <!--  contient la liste des privileges activee     -->
<div class="container">
        <img src="image/beaute.jpg" class="rounded float-left" alt="tof" width="200" height="200">
         <img src="image/crepe.jpg" class="rounded float-right" alt="tof" width="200" height="200">
         <br>
         <br>
          <h3 align="center" class="text-info "> <u>  Les Priviléges disponible  </u></h3>
<br>
<br>
<br>
  <table class="table table-hover">
  <br>
          <thead>
            <tr  class="table-succes">
              <th scoop="col"> Nom Privilége  </th>
              <th scope="col">Description </th>
              <th scope="col">Remise </th>
              <th scope="col">Date de Debut </th>
              <th scope="col">Date de Fin </th>
              <th scope="col">Marchand  </th>
            </tr>
          </thead>

               
          <tbody>
          @if(!is_null($priv_list))
            @foreach($priv_list as $key=>$value)
              <tr>
                <td>{{$value->nompriv}}</td>  
                <td>{{$value->descrip   }}</td>  
                <td>{{$value->remise  }}</td>  
                <td>{{$value->datedep }}</td>  
                <td>{{$value->datefin  }}</td> 
                <td>{{$value->marchand->nom  }}</td> 
              </tr> 
            @endforeach
          
        </tbody>

  </table>

@else
  <div class="alert alert-warning" role="alert" style="margin-top: 10px">
          <strong>Vous n'avez pas aucun privilege pour l'instant </strong>
  </div>  
@endif
<br>
<div class="alert alert-info" role="alert">
        Si Voulez modifier votre compte ! Cliquer Aussi  <a href="{{route('client.edit',$client->id)}}" class="alert-link"> Modifier</a>
</div>
<hr>
<a href="{{ route('logoutclient') }}" class="btn btn-warning" style="margin-bottom: 10px"> <u> Deconnexion </u></a>
<br>
</div>
@endsection

resources/views/frontoffice/createc.blade.php
@extends('frontoffice.acc')
@section('contents')
<div class="container" >
    <br>
    <br>

<h4 class="text-info"> <u> Inscription au Club </u> </h4>

@if ($errors->any())
    <div class="alert alert-danger">
        <strong>Whoops!</strong> Something went wrong<br>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
<hr>
<form  action="{{ route('client.store') }}" method="POST">
        {{ csrf_field() }}
    <div class="form-row">
      <div class="form-group col-md-6">
        <label> Nom <abbr class="required">*</abbr> </label>
           <input type="text" name="nom" value="{{ isset($client->nom) ? $client->nom : null }}" class="form-control">
      </div>
      <div class="form-group col-md-6">
        <label>Prénom <abbr class="required">*</abbr></label>
        <input type="text" class="form-control" name="prenom" placeholder="{{ isset($client->prenom) ? $client->prenom : null }}">
      </div>
    </div>
    <div class="form-group">
      <label>Email <abbr class="required">*</abbr></label>
      
      <input type="email" class="form-control" name="email" placeholder="{{ isset($client->email) ? $client->email : 'foulenbenFoulen@mail.com'}}">
    </div>
    <div class="fm-group">
      <label>Addresse</label>
      <input type="text" class="form-control" name="adresse" placeholder="{{ isset($client->adresse) ? $client->adresse : 'Saisir votre adresse'}}" >
    </div>
    <div class="form-row">
      <div class="form-group col-md-6">
        <label>Code Postal <abbr class="required">*</abbr></label>
        <input type="number" class="form-control" name="codepost" placeholder="{{ isset($client->codepost) ? $client->codepost: 'Saisir votre codepost'}}">
      </div>
      <div class="form-group col-md-4">
        <label>Date-Naissance <abbr class="required">*</abbr> </label>
        <input type="date" class="form-control" name="date_nais" min="1900-01-01" max="2019-12-31" value="{{ isset($client->date_nais) ? $client->date_nais: 'Saisir votre date_nais'}}" >
      </div>
      <div class="form-group col-md-2">
        <label>Télephone<abbr class="required">*</abbr></label>
        <input type="number" class="form-control" name="tel" placeholder="{{ isset($client->tel) ? $client->tel: 'Saisir votre telephone'}}">
      </div>
    </div>

            <div class="form-group">
            <div class="form-group col-md-6">
              <h4 class="text-info"> Modes de Paiement </h4>
            </div>
            <hr>
           </div>
            <div class="form-row">
                   <div class="form-group col-md-6" >
                       <br>
                    <h5 class="text-success" ><u> Paimenet par Carte  </u></h5>
                  </div>
                  <div class="form-group col-md-4">
                    <label> Numéro du carte <abbr class="required">*</abbr> </label>
                    <input type="number" class="form-control" name="carte_id">
                  </div>
                  <div class="form-group col-md-2">
                    <label> Code-Carte <abbr class="required">*</abbr> </label>
                    <input type="number" class="form-control" >
                  </div>
             </div>
             <div class="form-row">
                    <div class="form-group col-md-6" >
                        <br>
                     <h5 class="text-success" ><u> Ou bien Inscription Paimenet par nos PAYBOX  </u></h5>
                   </div>
             </div>
           <br>
           <br>
           <div class="form-row">
           <div class="form-group col-md-6" align="center">
                <br>
                <a href=""> <button  type="submit" class="btn btn-warning btn-lg btn-block">{{ isset($client) ? ' Modifier profile ' : 'Adhére au Club'}}</button> </a>
           </div>
           </div>

    <br>
    <br>
  </form>
</div>
@endsection

resources/views/frontoffice/createm.blade.php
@extends('frontoffice.acc')
@section('contents')

<div class="container" >
    <br>
    <br>

<h4 class="text-info"> <u> Inscription au Club </u> </h4>

@if ($errors->any())
    <div class="alert alert-danger">
        <strong>Whoops!</strong> Something went wrong<br>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
<hr>
<form  action="{{route('marchand.store')}}" method="post">
        @csrf
    <div class="form-row">
      <div class="form-group col-md-6">
        <label> Nom du commercant <abbr class="required">*</abbr> </label>
        <input type="nom" class="form-control" name="nom" placeholder="Nom ">
      </div>
      <div class="form-group col-md-4">
            <label>Télephone</label>
            <input type="number" class="form-control" name="tel" placeholder="Tél">
      </div>
    </div>
    <div class="form-row">
            <label> E-mail <abbr class="required">*</abbr></label>
            <input type="email" class="form-control" name="email" placeholder="Email">

    </div>
        <div class="form-group">

                <label> Liste des Adresse  <abbr class="required">*</abbr></label>
           <select class="custom-select" name="point_vente[]"  multiple="multiple">
            <option selected disabled >Sélectionner les Point-ventes</option>
            <option value="Ariana">Ariana</option>
            <option value="Bizerte">Bizerte</option>
            <option value="Ben arous">Ben arous</option>
            <option value="Tunis">Tunis</option>
            <option value="Jandouba">Jandouba</option>
            <option value="kef">kef</option>
          </select>
        </div>
        <hr width=100%>
        <div class="form-group">
                <div class="form-group col-md-4">
        <label> Mot de Passe  <abbr class="required">*</abbr> </label>
        <input type="password" class="form-control" name="motpass" >
      </div>
       <div class="form-group col-md-4">
        <label> Confirm mot de passe <abbr class="required">*</abbr></label>
        <input type="password" class="form-control" name="motpass">
      </div>
    </div>

            <br>
           <br>
           <div class="form-row">
                <br>
                <a href="{{url('marchandAcc')}}"> <button  type="submit" class="btn btn-warning btn-lg btn-block"> Inscription </button> </a>
           </div>
           </div>

    <br>
    <br>
  </form>
</div>

@endsection

resources/views/frontoffice/editm.blade.php
<!-- <?php 
?> -->
@extends('frontoffice.acc')
@section('contents')

<div class="container" >
    <br>
    <br>

<h4 class="text-info"> <u> Changer votre Informations </u> </h4>

@if ($errors->any())
    <div class="alert alert-danger">
        <strong>Whoops!</strong> Something went wrong<br>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
<hr>

<form  method="post" action="{{ route('update_marchand') }}">
  @csrf
    <div class="form-row">
      <div class="form-group col-md-6">
        <label> Nom du commercant <abbr class="required">*</abbr> </label>
        <input type="text" name="nom" class="form-control" value="{{ isset($marchand->nom) ? $marchand->nom : 'Nom'   }}" >
      </div>
      <div class="form-group col-md-4">
            <label>Télephone</label>
            <input type="text" name="tel" class="form-control" value="{{ isset($marchand->tel) ? $marchand->tel : 'tel'   }}">
      </div>
    </div>
    <div class="form-row">
            <label> E-mail <abbr class="required">*</abbr></label>
            <input type="text" class="form-control" name="email" value="{{ isset($marchand->email) ? $marchand->email : 'email'   }}">

    </div>
    <br>
        <div class="form-group">
          <label>Sélectionner les Point-ventes</label>
           <select class="custom-select" name="point_ventes"multiple>
            <!-- <option selected disabled ></option> -->
            <option value="Ariana">Ariana</option>
            <option value="Bizerte">Bizerte</option>
            <option value="Ben arous">Ben arous</option>
            <option value="Tunis">Tunis</option>
            <option value="Jandouba">Jandouba</option>
            <option value="kef">kef</option>

          </select>
        </div>
        <h4 class="text-warninig"> Changer le mot passe </h4>
        <br width=100%>
        <div class="form-group">
        <label> Mot de Passe  <abbr class="required">*</abbr> </label>
        <input type="password" class="form-control" name="motpass" placeholder="************" >
      </div>

    </div>

      <input type="submit" class="btn btn-info" value="Modifier "> 
      </div>
</form>
</div>

@endsection

resources/views/frontoffice/marchandAcc.blade.php
@extends('frontoffice.acc')
@section('contents')

<?php 
if (session()->has('marchand')){
  $marchand_id=session('marchand');
} 
else { ?>
  window.location.href={{url('/logasmarchand')}};  
<?php
}
?>
<br>
 <!--  contient la liste des  acheteur   -->
<div class="container">
@if (\Session::has('errors'))

    <div class="alert alert-danger">
        <strong>Whoops!</strong> Something went wrong<br>
        <div class="alert alert-danger" role="alert">
          {{ session('errors') }}
        </div>
    </div>
@endif
@if (\Session::has('success'))
    <div class="alert alert-success" role="alert">
        {{ session('success') }}
    </div>
@endif

        <img src="image/march.png" class="img-fluid" alt="Responsive image" height="100">
         <br>
         <br>
         <div class="form-row">
         <div class="form-group col-md-6">
          <h3 class="text-info "> <u>  Liste de mes  Acheteur   </u></h3>
     </div>
     <div class="form-group col-md-4">

<a href="{{url('marchand/ajout/acheteur/'.$marchand_id)}}" class="btn btn-outline-danger"> Ajouter Des Acheteurs </a>
</div>
 <div class="form-group col-md-2">
<a href="{{url('/Ajoutprivi')}}" ><button type="button" class="btn btn-outline-warning"> Ajouter  un Privilége </button></a>
</div>
</div>

<br>
<br>
<table class="table table-hover">
        <thead>
          <tr  class="table-succes">
            <th scoop="col">  Id carte </th>
            <th scope="col">Id-Privilege </th>
            <th scope="col">Adresse </th>
            <th scope="col">Date d'achat </th>
          </tr>
        </thead>

        <tbody>
          @if(!is_null($client_list))
            @foreach($client_list as $key=>$value)
              <tr>
                <td>{{$value->client_id}}</td>  
                <td>{{$value->privilege_id  }}</td>  
                <td>{{$value->Adresse }}</td>  
                <td>{{$value->created_at }}</td> 
              </tr> 
            @endforeach
          @endif
          
        </tbody>
</table>
<br>
<div class="alert alert-warning" role="alert">
        Si Voulez modifier votre compte ! Cliquer Aussi  <a href="{{route('marchand.show',$marchand_id)}}" class="alert-link"> Mofidier le Compte  </a>.
      </div>
<hr>
<!-- <a type=" button" " class="btn btn-light"> <u> Deconnexion </u></a> -->
<a href="{{ route('logoutmarchand') }}"  class="btn btn-primary"> Deconnexion </a>


<br>
</div>
@endsection